### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by kostyrevaa** [Nosmoht/ansible-library-foreman#10]
Hello there!
It seems to be interesting code, is it merged? Are there any plans to merge? How one can use it right now if it's not merge yet.
thanks!

**Comment by Nosmoht** [comment]
Hi,

just install the Python library on your Ansible control server and use the examples from README.MD.

Small example how i use it to deploy CoreOS Cluster:
```yaml
---
   - hosts: local
     connection: local
     gather_facts: false
     tasks:
     - name: Ensure CoreOS nodes
       foreman_host:
         name: '{{ item.name }}'
         build: true
        compute_profile: '{{ coreos_host_compute_profile }}'
        compute_resource: '{{ coreos_host_compute_resource }}'
        environment: production
        hostgroup: '{{ coreos_host_hostgroup }}'
        location: '{{ foreman_default_location }}'
        managed: true
        organization: '{{ foreman_default_organization }}'
        parameters: '{{ coreos_host_parameters }}'
        state: '{{ coreos_host_state }}'
        foreman_host: '{{ foreman_host }}'
        foreman_port: '{{ foreman_port }}'
        foreman_user: '{{ foreman_user }}'
        foreman_pass: '{{ foreman_pass }}'
```
